### PR TITLE
Unify related types together in `class SimilarTypes`

### PR DESCRIPTION
**Pull request by saytosid**
*Issue number of the reported bug or feature request: #33*

**Describe your changes**
Unified the list of related types -
https://github.com/bloomberg/attrs-strict/blob/c8052d9f9e76b7fd3515360eed9656b95bcba021/attrs_strict/_type_validation.py#L53-L67

**Testing performed**
This is a refactoring which should not have any functional change

**Additional context**
Split out from #25

### CODE REVIEW

**Comment by erikseulean** [comment]
Hmm, I'm not sure what's happening with the continuous documentation.

**Comment by erikseulean** [comment]
The docs are being rebuilt successfully on the pR: 

https://readthedocs.org/api/v2/build/11091145.txt

**Comment by erikseulean** [comment]
@kpfleming The continuous-documentation hook seems to be waiting for status indefinitely, but the build shows successful in readthedocs. I don't have access to check out the hook, would you mind checking it please ?

**Comment by erikseulean** [comment]
@gaborbernat any thoughts on the read-the-docs not getting back the update ?

**Comment by gaborbernat** [comment]
This goes with @kpfleming, seems there's a check mandated for merge... but that check was renamed from ``continuous-documentation/read-the-docs `` to ``
docs/readthedocs.org:attrs-strict ``. Branch protection needs to be updated, but only @kpfleming has the rights to do so.

**Comment by kpfleming** [comment]
All set...

**Comment by erikseulean** [comment]
Thank you @kpfleming @saytosid ❤️

**Pull request merged**
