### PR TITLE
Added funcsigs>=1.0.2 for python_version<3.5

### PR DESCRIPTION
**Pull request by lironhl**
#49 

**Describe your changes**
Added funcsigs package to setup.cfg, to be required when installing `attrs-strict` from python<3.5.

**Testing performed**
Ran the package in Python2.7 and in Python3.4 with funcsigs installed.

**additional context**
Even though Python 2.7.18 introduced `inspect` in the standard library it lacks the `signature` function used in this package.

### CODE REVIEW

**Comment by erikseulean** [comment]
Thanks for this. Checking why the lint is failing.

**Comment by erikseulean** [comment]
I think that step should use the python3.8 interpreter rather than the 3.7 one.

**Comment by gaborbernat** [comment]
https://github.com/bloomberg/attrs-strict/blob/master/.pre-commit-config.yaml#L14 should be python3.7, probably the underlying image we run changed and exposed this bug.

**Comment by erikseulean** [comment]
We can flip to run it using Python3.8, any downsides of that ?

**Comment by erikseulean** [comment]
@lironhl would you mind rebasing please, it should fix the build.

**Comment by lironhl** [comment]
> @lironhl would you mind rebasing please, it should fix the build.

Sorry for not being present in order to make the rebase myself, thank you for merging my changes!

**Pull request merged**
